### ISSUE TITLE
CRLFのファイルが扱えない

### ISSUE THREAD

**Issue by ruihe-umi** [gearsns/AozoraJavaScriptParser#1]
青空文庫からダウンロードしたテキストデータをそのまま読み込ませたところ、2行目以降全てauthorの扱い（h2.author）になり、冒頭の注記もそのまま出力されてしまいました。実行環境はWindows10+Firefox92,Chrome94です。

136～137行で変換前の処理するとき、`\n`でマッチさせているため、改行コードがCRLFのファイルをうまく扱えないことが原因だと思われます。事前にLFに変換してから読ませると注記も消え、HTMLと同様にレイアウトされました。`\r\n|\n`に変えた方が良いのではないでしょうか？

**Comment by gearsns** [comment]
バグの報告ありがとうございます。
CRLFへの対応を行いました。

**Comment by ruihe-umi** [comment]
早速のご対応ありがとうございます。きれいに変換されました👍
